server:
  error:
    include-message: always
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: admin
      password: password
      database: persocoach
      port: 27017
      host: localhost
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG