mongo:
    image: mymongo
    restart: always
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    app:
      - build: .
      - dockerfile: Dockerfile
      - ports :
          - "8085:8080"